Repository paldal-idol/BbangNyang, pull requests merged in 2021-07, with the labels that each got.

#9 feat : server 구조 변경, 대기방 유저 컴포넌트 분리
  client/src/components/molecules/WaitingRoomUsers.tsx
  client/src/pages/WaitingRoomPage.tsx
  server/app.ts
  server/index.ts
  server/package-lock.json
  server/package.json
  server/router/index.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end, 🧶 refactor

#8 feat : Rule Book 모달 추가
  client/package-lock.json
  client/src/components/atoms/Modal.tsx
  client/src/components/atoms/RuleBookButton.tsx
  client/src/components/molecules/RuleBookModal.tsx
  client/src/components/organisms/Bakery.tsx
  client/src/components/organisms/RuleBook.tsx
Labels: ✨ feature, 🐝 Front-end

#11 Feat chat
  client/package-lock.json
  client/package.json
  client/src/components/atoms/ChatInput.tsx
  client/src/components/atoms/ChatLog.tsx
  client/src/components/atoms/Loading.tsx
  client/src/components/atoms/Message.tsx
  client/src/components/atoms/Messages.tsx
  client/src/components/atoms/RoomList.tsx
  client/src/components/molecules/EntryCodeModal.tsx
  client/src/components/molecules/WaitingRoomChat.tsx
  client/src/components/molecules/WaitingRoomUsers.tsx
  client/src/pages/WaitingRoomPage.tsx
  client/src/store/room.ts
  client/src/store/user.ts
  client/src/store/users.ts
  client/webpack.config.js
  server/app.ts
  server/package-lock.json
  server/package.json
  server/socket/users.tsx
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end
